micronaut:
  application:
    name: enso
datasources:
  default:
    url: jdbc:postgresql://${ENSO_HOST}:${ENSO_PORT}/postgres
    driverClassName: org.postgresql.Driver
    username: ${ENSO_USER}
    password: ${ENSO_PASSWORD}
    schema-generate: NONE
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages: me.goudham.entity
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
bot:
  token: ${ENSO_TOKEN}
  guild:
    id: 621621615930638336
  config:
    registerCommands: false
    registerCommandsGlobally: false
    registerCommandsForGuild: true